apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    path: helm/cert-manager

    helm:
      valueFiles:
      - values-mac.yaml
  
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: cert-manager

  syncPolicy:
    automated:
      prune: true
      selfHeal: true