apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespace-manage
  namespace: argocd
spec:
  project: default
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    path: namespace

  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true