controller:

  image:
    repository: registry.cn-shanghai.aliyuncs.com/quay_mirror_image/kubernetes-ingress-controller.nginx-ingress-controller
    tag: "0.32.0"
    pullPolicy: IfNotPresent
    runAsUser: 101
    allowPrivilegeEscalation: true

  kind: DaemonSet
  hostNetwork: true

  daemonset:
    useHostPort: true

  resources:
    limits:
      cpu: 200m
      memory: 180Mi
    requests:
      cpu: 100m
      memory: 90Mi

  service:
    enabled: false

  admissionWebhooks:
    enabled: false

defaultBackend:
  enabled: true

  image:
    repository: registry.cn-shanghai.aliyuncs.com/gcr_mirror_image/defaultbackend-amd64
    tag: "1.5"
    pullPolicy: IfNotPresent
    runAsUser: 65534

  resources: 
    limits:
      cpu: 10m
      memory: 20Mi
    requests:
      cpu: 10m
      memory: 20Mi