apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: prometheus-ingress
  namespace: monitoring
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt-dns01
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: prometheus-operator-prometheus
          servicePort: web
    host: prometheus.local.ciii.tech
  tls:
  - secretName: prometheus-tls
    hosts:
      - prometheus.local.ciii.tech
    