replicaCount: 1

image:
  repository: registry.cn-shanghai.aliyuncs.com/quay_mirror_image/external_storage.nfs-client-provisioner
  tag: v3.1.0-k8s1.11
  pullPolicy: IfNotPresent

nfs:
  server: "192.168.0.1"
  path: "/"

storageClass:
  create: true
  name: nfs
  reclaimPolicy: Delete

rbac:
  create: true
  serviceAccountName: default

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
